### PR TITLE
Add 'since' haddock annotations to seconds <-> NominalDiffTime conversions

### PR DESCRIPTION
**Pull request by mgsloan**

### CODE REVIEW

**Comment by AshleyYakeley** [comment]
Hi, is it likely that other functions will need this sort of thing as well?

**Comment by AshleyYakeley** [comment]
Is the lack of them causing specific problems?

**Comment by hvr** [comment]
Not yet, but long-term they will be used for linting and suggesting `^>=`-style bounds

**Comment by AshleyYakeley** [comment]
In that case, it seems as if I should set a baseline, say 1.9, and annotate all later changes. Does that seem reasonable?

**Comment by hvr** [comment]
@AshleyYakeley yes, that sounds like a good way to get things moving; and that still leaves the option open to move that baseline backwards in time if people are willing to contribute complete `@since` annotations  for some earlier v1.x baseline

**Pull request merged**
