### PR TITLE
GHCJS patches.

### PR DESCRIPTION
**Pull request by alexanderkjeldaas**
Patches from the GHCJS project.

### CODE REVIEW

**Comment by AshleyYakeley** [comment]
How can I test this? I'm new the whole GHCJS thing.

**Comment by AshleyYakeley** [comment]
There seems to be quite a lot of duplication between the `__GHCJS__` part and the non-`__GHCJS__` part. What's actually different?

**Comment by alexanderkjeldaas** [comment]
I'm using docker to test this using a dockerfile like https://github.com/ghcjs/ghcjs/issues/652#issuecomment-388822035

Yes there seems to be some duplication.

**Comment by AshleyYakeley** [comment]
I couldn't build any version of GHCJS using stack.

Would you be able to provide how to make GHCJS fail without this PR, and succeed with it?

**Comment by AshleyYakeley** [comment]
This seems to be stale. Re-open if there's any update.

**Pull request closed without merging**
