### PR TITLE
Add Lift instances

### LINKED ISSUE #233: TH Lift instances for time types
Can we provide instances of `Language.Haskell.TH.Syntax.Lift` for types in `time`, like `UTCTime`, `DiffTime`, etc, so that time can be used in TH splices.
If there aren't major blockers (should `time` depend on `template-haskell`?), I'll be happy to submit a PR.

### PR DESCRIPTION
**Pull request by kokobd**
Closes #233 
- [x] add Lift instances to all time types
- [x] add tests
- [x] verify it's compatible across supported GHC/template-haskell versions

The code is not formatted with fourmolu, because existing code is not properly formatted. (I tried to call `fourmolu`, a lot of files changed)

### CODE REVIEW

**Comment by AshleyYakeley** [comment]
Probably better to put `DeriveLift` in the cabal file.

**Comment by AshleyYakeley** [comment]
Looks like WASM is already broken. I'll take a look.

**Comment by AshleyYakeley** [comment]
To format, run `./format-all -b`
It's a little awkward, it uses stack and my own fork of fourmolu. It changed one file, but I've added that to master now.

**Comment by AshleyYakeley** [comment]
I might just drop support of 8.10 (and add 9.4). It's pretty old.

**Comment by AshleyYakeley** [comment]
OK, don't worry about WASM, it's broken in master and I'll probably fix it after GHC 9.6 comes out.

**Comment by kokobd** [comment]
> Probably better to put DeriveLift in the cabal file.

Thank you, I'll do this.
> To format, run ./format-all -b

Ah, I was using the official fourmolu, that should be the cause.

**Comment by kokobd** [comment]
An import was added at the wrong position. I'll fix it later.

**Comment by kokobd** [comment]
This is ready for another review.

**Comment by AshleyYakeley** [comment]
Not sure what caused that build failure, maybe `tasty-quickcheck`?

**Comment by AshleyYakeley** [comment]
OK, build failure is in master too. I'll have a look at it.

**Comment by AshleyYakeley** [comment]
OK, master fixed.

**Comment by AshleyYakeley** [comment]
Merged, thanks!

**Comment by kokobd** [comment]
Cool!

**Pull request merged**
