### PR TITLE
Update autoconf to 2.71

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by AshleyYakeley** [comment]
Checking this on my local machine.

Why is the diff not matching identical lines? Different line endings maybe?

**Comment by AshleyYakeley** [comment]
Is this change needed for GHC? If so your PR should be directed to the `ghc` branch rather than the `master` branch.

**Comment by bgamari** [comment]
Indeed, the file now uses UNIX line endings.

> Is this change needed for GHC? If so your PR should be directed to the ghc branch rather than the master branch.

We currently get (and have been ignoring) warnings  from `autoconf` which this addresses. Fixing this isn't urgent though.

**Comment by AshleyYakeley** [comment]
OK, well this builds on my local machine so merging this.

The `ghc` branch is at 1.12.1 but I can do a 1.12.2 release in the next few days. Basically the `ghc` branch is the stable release branch, while the `master` branch is the working branch.

**Pull request merged**
