### PR TITLE
Make it compile with MicroHs

### PR DESCRIPTION
**Pull request by augustss**
Three kinds of changes:
- MicroHs does not have Generic
- MicroHs does not have Template Haskell
- MicroHs does not have pattern synonyms

### CODE REVIEW

**Comment by AshleyYakeley** [comment]
What's the best way of testing this? I'm worried this will break if it's not tested in CI.

**Comment by augustss** [comment]
I meant to add it to CI, but I forgot to do that.  I'll do that soon.

**Comment by AshleyYakeley** [comment]
Your CI failed. Looks like a shell arg-quoting issue or something.

**Comment by augustss** [comment]
Yes.  It needed a newer mhs version.  It's now using stable-2 instead of stable-1.

**Comment by AshleyYakeley** [comment]
Can you get CI to run the main test suite?

**Comment by augustss** [comment]
I'm not sure.  Does the other CI stuff do that?

**Comment by augustss** [comment]
I think it's a big fiddly to get it to run as part of the test suite.
You need to `git clone` the `mhs` repo, build `mhs`, and then compile.

**Comment by AshleyYakeley** [comment]
Ubuntu, MacOS, Windows and FreeBSD CI all run tests. WASM does not, because apparently tasty isn't supported, though it does run the (very small) ShowTime and ShowDefaultTZAbbreviations tests.

**Comment by AshleyYakeley** [comment]
Does MicroHs work with cabal?

**Comment by augustss** [comment]
I misunderstood. No, MHS can't run the test suite. It needs more stuff, e.g., tasty. 
But I'll see if I can add the simple tests.

**Comment by augustss** [comment]
"Does MicroHs work with Cabal?"
Depends on what you mean.

- Cabal can build the mhs binary.

- Cabal cannot use MHS to build libraries nor binaries. 

I've made MicroCabal which can use MHS (and GHC) to build stuff.

**Comment by augustss** [comment]
I've found some problems that I have to fix, so don't merge my changes yet.

**Comment by AshleyYakeley** [comment]
OK, I've converted it to draft. Convert it back when it's ready.

**Comment by augustss** [comment]
I think my changes are ready to be merged.

**Comment by augustss** [comment]
I don't know what format-all does, but I can test it. It uses stack, which I don't. But I'll install stack and see what happens.

**Comment by AshleyYakeley** [comment]
It runs `fourmolu` on the source files. However, `fourmolu` can't handle source files with CPP in them.

**Comment by AshleyYakeley** [comment]
Hmm, looks like `fourmolu` does have CPP support. In any case, don't worry about it.

**Comment by augustss** [comment]
Thanks!

Btw, I really hate adding CPP, but I don't know any other way. As MicroHaskell gets more features, some of them can be removed again.

**Comment by Bodigrim** [comment]
(Just passing by)

CPP can be done a little bit better using [`{-# LANGUAGE StandaloneDeriving #-}`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/standalone_deriving.html): instead of 
```haskell
newtype Month = MkMonth Integer deriving (Eq, Ord, Data, Typeable
#if __GLASGOW_HASKELL__
                                                                 , TH.Lift, Generic
#endif
                                                                                   )
```
one can write
```haskell
newtype Month = MkMonth Integer deriving (Eq, Ord, Data, Typeable)
#if __GLASGOW_HASKELL__
deriving instance TH.Lift Month
deriving instance Generic Month
#endif
```
This way CPP does not appear in the middle of declaration, making it easier for formatters and such simply ignore it.

As for `PatternSynonyms`, could MIcroHS support declaring them (which would be no-op, simply parse and ignore), but keep prohibiting their usage?

**Comment by AshleyYakeley** [comment]
Yup, currently working on this.

**Comment by augustss** [comment]
Adding parsing of pattern synonyms should be pretty easy. And then just ignoring them for now.

**Comment by augustss** [comment]
Actually, I could fake having deriving for TH.Lift and Generic as well. That would make for even fewer changes.  
Let me do that.

**Comment by augustss** [comment]
Regarding pattern synonyms. It's easy to just ignore the definitions to avoid CPP. But the synonyms are also frequently used, and those will still need CPP.

**Comment by AshleyYakeley** [comment]
Yeah that seems unavoidable, though in some cases I may be able to rewrite them.

Of course, you could just actually implement pattern synonyms in MicroHs...

**Pull request merged**
